# Cache node modules - speeds up future builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
stages:
  - build
  - deploy
variables:
  S3_BUCKET_DEV: ${BUCKET_DEV}
  S3_BUCKET_PROD: ${BUCKET_PROD}
  DIST_ID_DEV: ${CLOUDFRONT_DIST_ID_DEV}
  DIST_ID_PROD: ${CLOUDFRONT_DIST_ID_PROD}

.yarn_build_dev:
  image: node:18.18.2
  script: |
    yarn # Install dependencies
    yarn build --mode development # Build command
  artifacts:
    paths:
      - ./build

.yarn_build:
  image: node:18.18.2
  script: |
    yarn # Install dependencies
    yarn build # Build command
  artifacts:
    paths:
      - ./build

yarn_dev:
  extends: .yarn_build_dev
  stage: build
  only:
    refs:
      - develop
yarn_prod:
  extends: .yarn_build
  stage: build
  before_script:
    - export APP_ENV="prod"
  only:
    refs:
      - main
.deploy_aws:
  image: python:latest
  when: always
  script: |
    pip install awscli
    aws s3 sync ./build/ s3://${S3_BUCKET}
    aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DIST_ID} --paths "/*"
deploy_dev:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - yarn_dev
  before_script:
    - export S3_BUCKET=${S3_BUCKET_DEV}
    - export CLOUDFRONT_DIST_ID=${DIST_ID_DEV}
  only:
    refs:
      - develop
deploy_prod:
  extends: .deploy_aws
  stage: deploy
  dependencies:
    - yarn_prod
  before_script:
    - export S3_BUCKET=${S3_BUCKET_PROD}
    - export CLOUDFRONT_DIST_ID=${DIST_ID_PROD}
  only:
    refs:
      - main
